# Generated by Django 3.2 on 2021-04-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carrinho',
            managers=[
            ],
        ),
    ]
