# Generated by Django 3.2 on 2021-04-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0002_alter_carrinho_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
