# Generated by Django 3.2 on 2021-04-24 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_alter_produto_nome'),
        ('supermercado', '0003_delete_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField(auto_created=True, default=True, verbose_name='Pago')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator('carrinho')])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercado.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produto', verbose_name='Produto')),
            ],
        ),
    ]
