# Generated by Django 3.2 on 2021-04-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(auto_created=True, default=True)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Pago')),
                ('data_criada', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
