# Generated by Django 3.2 on 2021-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210421_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_medio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Preço Atacado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Preço Venda'),
            preserve_default=False,
        ),
    ]
